// Code generated by MockGen. DO NOT EDIT.
// Source: ./service_client_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	vo "github.com/peggypig/nacos-go/vo"
	reflect "reflect"
)

// MockIServiceClient is a mock of IServiceClient interface
type MockIServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceClientMockRecorder
}

// MockIServiceClientMockRecorder is the mock recorder for MockIServiceClient
type MockIServiceClientMockRecorder struct {
	mock *MockIServiceClient
}

// NewMockIServiceClient creates a new mock instance
func NewMockIServiceClient(ctrl *gomock.Controller) *MockIServiceClient {
	mock := &MockIServiceClient{ctrl: ctrl}
	mock.recorder = &MockIServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIServiceClient) EXPECT() *MockIServiceClientMockRecorder {
	return m.recorder
}

// RegisterServiceInstance mocks base method
func (m *MockIServiceClient) RegisterServiceInstance(param vo.RegisterServiceInstanceParam) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterServiceInstance", param)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterServiceInstance indicates an expected call of RegisterServiceInstance
func (mr *MockIServiceClientMockRecorder) RegisterServiceInstance(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterServiceInstance", reflect.TypeOf((*MockIServiceClient)(nil).RegisterServiceInstance), param)
}

// LogoutServiceInstance mocks base method
func (m *MockIServiceClient) LogoutServiceInstance(param vo.LogoutServiceInstanceParam) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogoutServiceInstance", param)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogoutServiceInstance indicates an expected call of LogoutServiceInstance
func (mr *MockIServiceClientMockRecorder) LogoutServiceInstance(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogoutServiceInstance", reflect.TypeOf((*MockIServiceClient)(nil).LogoutServiceInstance), param)
}

// ModifyServiceInstance mocks base method
func (m *MockIServiceClient) ModifyServiceInstance(param vo.ModifyServiceInstanceParam) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyServiceInstance", param)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModifyServiceInstance indicates an expected call of ModifyServiceInstance
func (mr *MockIServiceClientMockRecorder) ModifyServiceInstance(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyServiceInstance", reflect.TypeOf((*MockIServiceClient)(nil).ModifyServiceInstance), param)
}

// GetService mocks base method
func (m *MockIServiceClient) GetService(param vo.GetServiceParam) (vo.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService", param)
	ret0, _ := ret[0].(vo.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetService indicates an expected call of GetService
func (mr *MockIServiceClientMockRecorder) GetService(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockIServiceClient)(nil).GetService), param)
}

// GetServiceInstance mocks base method
func (m *MockIServiceClient) GetServiceInstance(param vo.GetServiceInstanceParam) (vo.ServiceInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceInstance", param)
	ret0, _ := ret[0].(vo.ServiceInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceInstance indicates an expected call of GetServiceInstance
func (mr *MockIServiceClientMockRecorder) GetServiceInstance(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceInstance", reflect.TypeOf((*MockIServiceClient)(nil).GetServiceInstance), param)
}

// StartBeatTask mocks base method
func (m *MockIServiceClient) StartBeatTask(param vo.BeatTaskParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartBeatTask", param)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartBeatTask indicates an expected call of StartBeatTask
func (mr *MockIServiceClientMockRecorder) StartBeatTask(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartBeatTask", reflect.TypeOf((*MockIServiceClient)(nil).StartBeatTask), param)
}

// StopBeatTask mocks base method
func (m *MockIServiceClient) StopBeatTask() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopBeatTask")
}

// StopBeatTask indicates an expected call of StopBeatTask
func (mr *MockIServiceClientMockRecorder) StopBeatTask() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopBeatTask", reflect.TypeOf((*MockIServiceClient)(nil).StopBeatTask))
}

// GetServiceDetail mocks base method
func (m *MockIServiceClient) GetServiceDetail(param vo.GetServiceDetailParam) (vo.ServiceDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceDetail", param)
	ret0, _ := ret[0].(vo.ServiceDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceDetail indicates an expected call of GetServiceDetail
func (mr *MockIServiceClientMockRecorder) GetServiceDetail(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceDetail", reflect.TypeOf((*MockIServiceClient)(nil).GetServiceDetail), param)
}
